#! /opt/homebrew/bin/python3

import sys, json
import openai

if not len(sys.argv) == 2:
    print("chat \"Explain how pi is calculated.\"")
    sys.exit(1)

memory = {}
try:
    with open(".chat", "r") as file:
        memory = json.load(file)
except (IOError, json.decoder.JSONDecodeError):
    pass

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": memory.get("query", "")},
        {"role": "assistant", "content": memory.get("response", "")},
        {"role": "user", "content": sys.argv[1]}
    ]
)
response = response["choices"][0]["message"]["content"]
print(response)

with open(".chat", "w") as file:
    memory = {"query" : sys.argv[1], 
            "response" : response}
    json.dump(memory, file, indent=4, ensure_ascii=False)
